services:
  backend:
    build: ./backend    
    env_file:
      - .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./backend/system:/app/system
    container_name: login-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  # frontend:
  #   build: ./frontend
  #   env_file:
  #     - .env
  #   container_name: login-frontend
  #   environment:
  #     - FRONTEND_PORT=${FRONTEND_PORT}
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  mysql_db:
    build: ./mysql
    env_file:
      - .env
    container_name: mysql
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"