services:
  auth-service:
    build: ./backend/auth-service    
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    volumes:
      - ./backend/core:/app/core
      - ./backend/auth-service/model:/app/model
      - ./backend/auth-service/router:/app/router
      - ./backend/auth-service/test:/app/test
      - ./backend/auth-service/controller:/app/controller
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    networks:
      - app-network
  expense-service:
    build: ./backend/expense-service
    env_file:
      - .env
    environment:
      - EXPENSE_SERVICE_PORT=${EXPENSE_SERVICE_PORT}
    volumes:
      - ./backend/core:/app/core
      - ./backend/expense-service/model:/app/model
      - ./backend/expense-service/router:/app/router
      - ./backend/expense-service/test:/app/test
      - ./backend/expense-service/controller:/app/controller
    container_name: expense-service
    ports:
      - "${EXPENSE_SERVICE_PORT}:${EXPENSE_SERVICE_PORT}"
    networks:
      - app-network
  nginx:
    build: ./nginx
    env_file:
      - .env
    container_name: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs 
    depends_on:
      - auth-service
      - expense-service
      - mysql_db
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    networks:
      - app-network
  mysql_db:
    build: ./mysql
    env_file:
      - .env
    container_name: mysql
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/mysql_data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge