worker_processes 2;

events {
    worker_connections 1024;
}
http {
    server {
        listen ${FRONTEND_PORT};
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
            include /etc/nginx/mime.types;
        }
        error_log  /var/log/nginx/client-error.log;
        access_log /var/log/nginx/client-access.log;
    }
}