mysql_db:
  MYSQL_USER: root
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  USER_DB: user_db
  HOST: mysql_db
  DATABASE_PORT: ${DATABASE_PORT}
JWT:
  SECRET_KEY: ${TOKEN_SECRET_KEY}
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: 30